# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: websocket.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'websocket.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwebsocket.proto\x12\x13\x66leet.proto.message\"\xcd\x01\n\x07Message\x12\x34\n\x04type\x18\x01 \x01(\x0e\x32 .fleet.proto.message.MessageTypeR\x04type\x12\x1d\n\x07\x61\x64\x64ress\x18\x02 \x01(\tH\x00R\x07\x61\x64\x64ress\x88\x01\x01\x12\x1c\n\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x12\n\x04\x64\x61ta\x18\x04 \x01(\x0cR\x04\x64\x61ta\x12!\n\tsignature\x18\x05 \x01(\x0cH\x01R\tsignature\x88\x01\x01\x42\n\n\x08_addressB\x0c\n\n_signature\"H\n\x0c\x42\x61tchMessage\x12\x38\n\x08messages\x18\x01 \x03(\x0b\x32\x1c.fleet.proto.message.MessageR\x08messages\"`\n\x05State\x12\x12\n\x04type\x18\x01 \x01(\tR\x04type\x12\x43\n\nattributes\x18\x02 \x03(\x0b\x32#.fleet.proto.message.StateAttributeR\nattributes\"8\n\x0eStateAttribute\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value\"@\n\nBatchState\x12\x32\n\x06states\x18\x01 \x03(\x0b\x32\x1a.fleet.proto.message.StateR\x06states*(\n\x0bMessageType\x12\x0b\n\x07REQUEST\x10\x00\x12\x0c\n\x08RESPONSE\x10\x01\x42\tZ\x07./typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'websocket_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./types'
  _globals['_MESSAGETYPE']._serialized_start=544
  _globals['_MESSAGETYPE']._serialized_end=584
  _globals['_MESSAGE']._serialized_start=41
  _globals['_MESSAGE']._serialized_end=246
  _globals['_BATCHMESSAGE']._serialized_start=248
  _globals['_BATCHMESSAGE']._serialized_end=320
  _globals['_STATE']._serialized_start=322
  _globals['_STATE']._serialized_end=418
  _globals['_STATEATTRIBUTE']._serialized_start=420
  _globals['_STATEATTRIBUTE']._serialized_end=476
  _globals['_BATCHSTATE']._serialized_start=478
  _globals['_BATCHSTATE']._serialized_end=542
# @@protoc_insertion_point(module_scope)
